### ISSUE TITLE
Story Page Error 

### ISSUE THREAD

**Issue by halper03** [yakovlevvl/Instories#1]
Hello.
Story page view detail error. Please help me.
<img width="882" alt="Ekran Resmi 2020-01-23 10 02 33" src="https://user-images.githubusercontent.com/14207566/72963273-da641600-3dc7-11ea-80a4-ac9cc145a188.png">

**Comment by ucelme** [comment]
I came to the same problem. App crash. Is any solution to fix this?

**Comment by yakovlevvl** [comment]
Hi, the app fixed for iOS 13, check new release.
